spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dealsdata
    username: postgres
    password: postgres
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    generate-ddl: true
